### ISSUE TITLE
Cannot make commit after `make start` command

### ISSUE THREAD

**Issue by paaneko** [VilnaCRM-Org/user-service#38]
### Description
After running `make start` command, developers are prevented from making commits. However, commits work fine in a clean project that was just cloned.
The issue persists even after running the `make down` command.

### Steps to Reproduce
1. clone git repository
2. make any commit
3. observe that the commit is successful.
4. run `make start` command
5. try to make commit again
6. see error `env: php: No such file or directory`

### Additional info
After removing vendor folder and try to commit again, it shows new error `.git/hooks/pre-commit: line 17: vendor/bin/captainhook: No such file or directory`.
Probably this happen, because `captainHook` trying to execute himself using php on local machine not from docker container.

### Environment
- **OS:** [MacOS]
- **Console** [Iterm2, PHPStrom build in console]
- **PHP** [PHP not installed on host machine]

**Comment by paaneko** [comment]
```
"config": {
        "run": {
            "mode": "docker",
            "exec": "docker compose exec -i php"
        }
    },
```

Can be fixed by this in `captainhook.json`

**Comment by Kravalg** [comment]
@Derane please test this and write what is behaviour on your machine
